// <auto-generated />
using Demo.WalletManagement.Api.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Demo.WalletManagement.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240501080337_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Demo.WalletManagement.Api.Models.Domain.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "First Account",
                            AccountNumber = "001424244540",
                            Balance = 500.0
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "Second Account",
                            AccountNumber = "5256344540",
                            Balance = 400.0
                        },
                        new
                        {
                            Id = 3,
                            AccountName = "Third Account",
                            AccountNumber = "425424244540",
                            Balance = 540.0
                        },
                        new
                        {
                            Id = 4,
                            AccountName = "Fourth Account",
                            AccountNumber = "7014251244540",
                            Balance = 70.0
                        },
                        new
                        {
                            Id = 5,
                            AccountName = "Fifth Account",
                            AccountNumber = "101424244540",
                            Balance = 10000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
